version: '3.4'

services:
  expresstypescript:
    image: dataset9
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 2023:2023
