version: '3.4'

services:
  expresstypescript:
    image: expresstypescript
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 2023:2023
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/index.js"]
